fastpay:
  hostname: http://localhost:9995
  public-token: tDBmh0ZiDrmaZ8BVQD7i9UYdcj9KtZUk
  private-token: SSEewtC6Ps5yJLdB6SJmh1bqJXgRbCdf8ocDj2hU

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fastpay
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false
    locations: classpath:db/migration
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/fastpay