fastpay:
  hostname: https://fastpay.algashop.com #deve ser o DNS
  #token fixo apenas para simulação - deve ser o mesmo no ecommerce web app
  public-token: tDBmh0ZiDrmaZ8BVQD7i9UYdcj9KtZUk
  #token fixo apenas para simulação - deve ser o mesmo no payment-service
  private-token: SSEewtC6Ps5yJLdB6SJmh1bqJXgRbCdf8ocDj2hU

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost:3306}/fastpay?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:mysql}
  jpa:
    hibernate:
      ddl-auto: update #Esse projeto as migrations não ficaram prontas, mas deveria ter!
    show-sql: false