fastpay:
  hostname: ${FASTPAY_HOSTNAME}
  public-token: ${FASTPAY_PUBLIC_TOKEN}
  private-token: ${FASTPAY_PRIVATE_TOKEN}

spring:
  datasource:
    url: ${DATABASE_JDBC_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: ${FLYWAY_DATABASE_JDBC_URL:jdbc:postgresql://algashop-postgres:5432/fastpay}
    user: ${FLYWAY_DATABASE_USERNAME}
    password: ${FLYWAY_DATABASE_PASSWORD}