fastpay:
  hostname: http://localhost:9995
  public-token: tDBmh0ZiDrmaZ8BVQD7i9UYdcj9KtZUk
  private-token: SSEewtC6Ps5yJLdB6SJmh1bqJXgRbCdf8ocDj2hU

server:
  port: 9995

spring:
  application:
    name: fastpay
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost:3306}/fastpay?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:mysql}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false