fastpay:
  tokenized-card-expires-in: 2m

server:
  port: 9995

spring:
  application:
    name: fastpay
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration