fastpay:
  hostname: ${FASTPAY_HOSTNAME:http://localhost:9995}

spring:
  datasource:
    url: ${DATABASE_JDBC_URL:jdbc:postgresql://algashop-postgres:5432/fastpay}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  flyway:
    url: ${DATABASE_JDBC_URL:jdbc:postgresql://algashop-postgres:5432/fastpay}
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
